### PR TITLE
Allow async resolution for autocompletion

### PR DESCRIPTION
**Pull request by takion**

### CODE REVIEW

**Comment by f** [comment]
Wow, nice feature! May you add an example to the README?

**Comment by takion** [comment]
Done

**Comment by f** [comment]
Thank you!

**Comment by takion** [comment]
You're welcome ;)
thank to you for your awesome library !

**Comment by f** [comment]
Ops, I needed to revert the PR :(

**Comment by f** [comment]
Update: https://github.com/f/omelette#async-api- I rewrote the PR by adding `.next` method. Since it's async, the main program was not working as required. Please see the readme.

**Pull request merged**
