### PR TITLE
Remove ':' as word breaker on bash so we can autocomplete commands with ':' in them

### PR DESCRIPTION
**Pull request by jblandry**

### CODE REVIEW

**Comment by f** [comment]
Is it possible to make this improvement for other shells?

**Comment by jblandry** [comment]
Unfortunately I've never used any other shell than Bash :(

**Comment by f** [comment]
Can someone confirm if it's working?

**Comment by jblandry** [comment]
It's working 😛

**Comment by YannBergonzat** [comment]
I can confirm it's working on bash

**Comment by benoitrenaud** [comment]
It works well for me

**Comment by f** [comment]
I trust all you guys and merged 👍

**Pull request merged**
